server:
  port: 8765
spring:  application:    name: hr-api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:  routes:    worker:
      service-id: hr-worker
      path: /hr-worker/**
    payroll:
      service-id: hr-payroll
      path: /hr-payroll/**